### ISSUE TITLE
Search fails when results page shows no total

### ISSUE THREAD

**Issue by alanbernstein** [anthonyhseb/googlesearch#8]
* google-search version: 1.0.2
* Python version: 2.7.13
* Operating System: macOS 10.12.6

### Description

I'm using a simple test script, barely modified from the example in the readme. I think the TOTAL_SELECTOR is missing from the results page, which seems to happen when Google displays "card" results (or whatever those are called). You can see an example with the query "danny elfman emmy award":

<img width="656" alt="screen shot 2018-01-23 at 10 44 43 am" src="https://user-images.githubusercontent.com/16123214/35288493-78b70ca0-002a-11e8-81c6-a9c248c064b4.png">

This could presumably be fixed by checking for the presence of the selector. However, I am interested in the total count as well, so I'm wondering if you have any ideas for another way to get that, for queries that trigger the "card" display.

### What I Did

```
Traceback (most recent call last):
  File "google_search_test.py", line 21, in <module>
    r = GoogleSearch().search(query, prefetch_pages=False)
  File "/Users/abernstein/venvs/0/lib/python2.7/site-packages/googlesearch/googlesearch.py", line 39, in search
    totalText = soup.select(GoogleSearch.TOTAL_SELECTOR)[0].children.next().encode('utf-8')
IndexError: list index out of range
```

**Comment by anthonyhseb** [comment]
Thanks for reporting this issue Alan. Unfortunately I am very busy working on my thesis at the moment. Indeed a scraping tool like googlesearch needs constant maintenance since the website markup keeps evolving. The source code under googlesearch/googlesearch.py contains all the logic. You may for example use your own custom version of the code instead of the current release by uninstalling it using pip, and installing your own version instead using setuputils (python setup.py).

If you'd like to suggest a pull request it would be more than welcome :) (please make sure it passes the Tox tests).

Best,
Anthony

**Comment by ilteriskesk** [comment]
Thanks for redirect :) I will try say. Good work :)

İlteriş


2018-02-19 21:40 GMT+03:00 anthonyhseb <notifications@github.com>:
